### PR TITLE
Load current projectId for every route

### PR DESCRIPTION
**Pull request by hungnguyen94**
This will resolve the currentProjectId before the pages are loaded. To get the current project id, you only need to include the `currentProject` dependency in the controller. 

When the user is not logged in, it will return `null`.

### CODE REVIEW

**Comment by ChrisBerg** [comment]
Nice solution, easy to reuse. No comments on the code

**Comment by rubenwiersma** [comment]
Travis CI build failed, needs fixing

**Comment by hungnguyen94** [comment]
The JavaScript tests seem to be failing. I'll look into that.

**Comment by hungnguyen94** [comment]
Should be fixed now. I accidently added `ngAnimate` to app.module.js, which is not needed for this feature. `ngAnimate` isn't defined anywhere, so it caused errors.

**Pull request merged**
